platform :ios, '9.0'
use_frameworks!
pod 'SwiftyJSON'
pod 'Alamofire'
pod 'SnapKit'
pod 'XCGLogger', '~> 3.2'
pod 'Kingfisher'
pod 'UITableView+FDTemplateLayoutCell'
pod 'OAuthSwift'
pod 'ReachabilitySwift', :git => 'https://github.com/ashleymills/Reachability.swift'
pod 'AlamofireObjectMapper', '~> 2.1'
pod 'ObjectMapper'